const Router = require('koa-router')
const router = new Router().prefix('/template')
const templateController = require('../controllers/template.controller')
const body = require('koa-better-body');

router.get('/openorcreate', templateController.openOrCreate)
router.post('/changetitle', templateController.changeTitle)
router.post('/changeimage', templateController.changeImage)
router.get('/createstorylevel', templateController.createStoryLevel)
router.post('/deletelevel', templateController.deleteLevel)
router.post('/addchaptertostorylevel', templateController.addChapterToStoryLevel)
router.post('/deletechapterinstorylevel', templateController.deleteChapterInStoryLevel)
router.post('/createchapter', templateController.createChapter)
router.post('/changechapter', templateController.changeChapter)
router.post('/deletechapter', templateController.deleteChapter)
router.post('/createdecision', templateController.createDecision)
router.get('/refreshneed', templateController.refreshNeed)
router.post('/changeneed', templateController.changeNeed)
router.get('/refreshdevision', templateController.refreshDecision)
router.post('/changedecision', templateController.changeDecision)
router.post('/deletedecision', templateController.deleteDecision)
router.post('/createcounter', templateController.createCounter)
router.post('/changecounter', templateController.changeCounter)
router.post('/deletecounter', templateController.deleteCounter)
router.get('/checktemplateerrors', templateController.checkTemplateErrors)

module.exports = router.routes()